### ISSUE TITLE
Validate the feature set and code review 

### ISSUE THREAD

**Issue by xavier506** [eosinabox/eosinabox#1]
- [ ] QA the current featureset
- [ ] Security Audit / Testing (cross origin testing)
- [ ] Code Quality of backend services (dDOS) 
- [ ] Code injections test 
- [ ] Dependencies graph check

**Comment by amih** [comment]
Thank you @xavier506 !

Please split these into 2 separate issues in the future, this will help deal with them separately.

* I updated the code to prevent the duplicate entry in the account list. You need to refresh twice for any update in the code to take effect, this is due to the PWA local cache.
* The Anchor issue is in Anchor wallet, they need to fix it, they don't yet support WebAuthn public keys in Anchor. See related issue there: https://github.com/greymass/anchor/issues/1190

**Comment by amih** [comment]
I will separate these issues so it will be easier to manage, discuss and close each one on its own

**Comment by amih** [comment]
Separated all the issues in this thread to their own issue ticket so I can close them one by one.
